(function(){var a=["http://ers.baidu.com/app/s.js?siteId=1590335&subjectId=0&goTop=1"];for(var i=0;i<1;i++){var s=document.createElement("script");s.type="text/javascript";s.charset="utf-8";s.async=true;s.src=a[i];var s0=document.getElementsByTagName("script")[0];s0.parentNode.insertBefore(s,s0);}})();(function(){var c={id:"9b238846a07d7a339bd98b95c0e61213",dm:["verydemo.com"],etrk:[],js:"tongji.baidu.com/hm-web/js/",icon:'',br:false,ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:1,rp:[],trust:0,vcard:0,se:[]};
var l=!0,m=null,n=!1;var p;
(p=function(){function a(){if(!a.d){a.d=l;for(var b=0,d=e.length;b<d;b++)e[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(b,1);return}a()}var d=n,e=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,n);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!d)if(d=l,"complete"===document.readyState)a.d=l;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,
n),window.addEventListener("load",a,n);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var e=n;try{e=window.frameElement==m}catch(h){}document.documentElement.doScroll&&e&&b()}})();return function(b){a.d?b():e.push(b)}}()).d=n;var r=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===m)return"null";if(d instanceof Array){var f=["["],g=d.length,h,k,q;for(k=0;k<g;k++)switch(q=d[k],typeof q){case "undefined":case "function":case "unknown":break;default:h&&f.push(","),f.push(r(q)),h=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';h=["{"];for(g in d)if(Object.prototype.hasOwnProperty.call(d,g))switch(k=d[g],typeof k){case "undefined":case "unknown":case "function":break;
default:f&&h.push(","),f=1,h.push(r(g)+":"+r(k))}h.push("}");return h.join("")}}}();var aa=/msie (\d+\.\d+)/i.test(navigator.userAgent),ba=navigator.cookieEnabled,ca=navigator.javaEnabled(),da=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"",ea=(window.screen.width||0)+"x"+(window.screen.height||0),fa=window.screen.colorDepth||0;function s(a,b,d){var e;d.f&&(e=new Date,e.setTime(e.getTime()+d.f));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.p?"; secure":"")};function v(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(d){}}function w(a){return window.sessionStorage?window.sessionStorage.getItem(a):m};function B(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,n)};function C(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:m}function D(a){return(a=(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):m)?a.replace(/:\d+$/,""):a};function E(a,b){return"[object "+b+"]"==={}.toString.call(a)};var F;function I(){if(!F)try{F=document.createElement("input"),F.type="hidden",F.style.display="none",F.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(F)}catch(a){return n}return l}
function ga(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):I()&&(F.expires=e.toUTCString(),F.load(document.location.hostname),F.setAttribute(a,b),F.save(document.location.hostname))}catch(f){}}
function la(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(I())try{return F.load(document.location.hostname),F.getAttribute(a)}catch(e){}return m};function L(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=m;d=window[e]=m;b&&b(a)};d.src=a};var M=0,Q=Math.round(+new Date/1E3),R="https:"==document.location.protocol?"https:":"http:",ma="cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ");function S(){if("undefined"==typeof window["_bdhm_loaded_"+c.id]){window["_bdhm_loaded_"+c.id]=l;var a=this;a.a={};a.b=[];a.o={push:function(){a.l.apply(a,arguments)}};a.e=0;a.g=n;na(a)}}
S.prototype={getData:function(a){try{var b=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie);return(b?b[2]:m)||w(a)||la(a)}catch(d){}},setData:function(a,b,d){try{s(a,b,{domain:oa(),path:pa(),f:d}),d?ga(a,b,d):v(a,b)}catch(e){}},l:function(a){if(E(a,"Array")){var b=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a},d=function(a){for(var b in a)if({}.hasOwnProperty.call(a,b)){var e=a[b];E(e,"Object")||E(e,"Array")?d(e):a[b]=String(e)}};switch(a[0]){case "_trackPageview":if(1<
a.length&&a[1].charAt&&"/"==a[1].charAt(0)){this.a.api|=4;this.a.et=0;this.a.ep="";this.g?(this.a.nv=0,this.a.st=4):this.g=l;var b=this.a.u,e=this.a.su;this.a.u=R+"//"+document.location.host+a[1];this.a.su=document.location.href;T(this);this.a.u=b;this.a.su=e}break;case "_trackEvent":2<a.length&&(this.a.api|=8,this.a.nv=0,this.a.st=4,this.a.et=4,this.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),T(this));break;case "_setCustomVar":if(4>a.length)break;var e=a[1],f=a[4]||3;if(0<
e&&6>e&&0<f&&4>f){this.e++;for(var g=(this.a.cv||"*").split("!"),h=g.length;h<e-1;h++)g.push("*");g[e-1]=f+"*"+b(a[2])+"*"+b(a[3]);this.a.cv=g.join("!");a=this.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?this.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):qa()}break;case "_trackOrder":a=a[1];E(a,"Object")&&(d(a),this.a.api|=16,this.a.nv=0,this.a.st=4,this.a.et=94,this.a.ep=r(a),T(this));break;case "_trackMobConv":if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])this.a.api|=
32,this.a.et=93,this.a.ep=a,T(this);break;case "_trackRTPageview":a=a[1];E(a,"Object")&&(d(a),a=r(a),512>=encodeURIComponent(a).length&&(this.a.api|=64,this.a.rt=a));break;case "_trackRTEvent":a=a[1],E(a,"Object")&&(d(a),a=r(a),1024>=encodeURIComponent(a).length&&(b=this.a.rt,this.a.api|=128,this.a.et=90,this.a.rt=a,T(this),this.a.rt=b))}}}};
function ra(){var a=w("Hm_unsent_"+c.id);if(a)for(var a=a.split(","),b=0,d=a.length;b<d;b++)L(R+"//"+decodeURIComponent(a[b]).replace(/^https?:\/\//,""),function(a){U(a)})}function U(a){var b=w("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?v("Hm_unsent_"+c.id,b):window.sessionStorage&&window.sessionStorage.removeItem("Hm_unsent_"+c.id))}
function sa(a,b){var d=w("Hm_unsent_"+c.id)||"",e=a.a.u?"":"&u="+encodeURIComponent(document.location.href),d=encodeURIComponent(b.replace(/^https?:\/\//,"")+e)+(d?","+d:"");v("Hm_unsent_"+c.id,d)}function T(a){a.a.rnd=Math.round(2147483647*Math.random());a.a.api=a.a.api||a.e?a.a.api+"_"+a.e:"";var b=R+"//hm.baidu.com/hm.gif?"+ta(a);a.a.api=0;a.e=0;sa(a,b);L(b,function(a){U(a)})}function ua(a){return function(){a.a.nv=0;a.a.st=4;a.a.et=3;a.a.ep=va.n()+","+va.m();T(a)}}
function na(a){try{var b,d,e,f,g,h,k;M=a.getData("Hm_lpvt_"+c.id)||0;13==M.length&&(M=Math.round(M/1E3));if(document.referrer){var q=n;if(Y(document.referrer)&&Y(document.location.href))q=l;else var G=D(document.referrer),q=Z(G||"",document.location.hostname);d=q?Q-M>c.vdur?1:4:3}else d=Q-M>c.vdur?1:4;b=4!=d?1:0;if(h=a.getData("Hm_lvt_"+c.id)){k=h.split(",");for(var t=k.length-1;0<=t;t--)13==k[t].length&&(k[t]=""+Math.round(k[t]/1E3));for(;2592E3<Q-k[0];)k.shift();g=4>k.length?2:3;for(1===b&&k.push(Q);4<
k.length;)k.shift();h=k.join(",");f=k[k.length-1]}else h=Q,f="",g=1;a.setData("Hm_lvt_"+c.id,h,c.age);a.setData("Hm_lpvt_"+c.id,Q);e=Q==a.getData("Hm_lpvt_"+c.id)?"1":"0";if(0==c.nv&&Y(document.location.href)&&(""==document.referrer||Y(document.referrer)))b=0,d=4;a.a.nv=b;a.a.st=d;a.a.cc=e;a.a.lt=f;a.a.lv=g;a.a.si=c.id;a.a.su=document.referrer;a.a.ds=ea;a.a.cl=fa+"-bit";a.a.ln=da;a.a.ja=ca?1:0;a.a.ck=ba?1:0;a.a.lo="number"==typeof _bdhm_top?1:0;var x=a.a;b="";if(navigator.plugins&&navigator.mimeTypes.length){var u=
navigator.plugins["Shockwave Flash"];u&&u.description&&(b=u.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{var J=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");J&&(b=J.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(Da){}x.fl=b;a.a.v="1.0.63";a.a.cv=decodeURIComponent(a.getData("Hm_cv_"+c.id)||"");1==a.a.nv&&(a.a.tt=document.title||"");a.a.api=0;var K=document.location.href;a.a.cm=C(K,"hmmd")||"";a.a.cp=C(K,"hmpl")||"";a.a.cw=C(K,
"hmkw")||"";a.a.ci=C(K,"hmci")||"";a.a.cf=C(K,"hmsr")||"";0==a.a.nv?ra():U(".*");if(""!=c.icon){var y,z=c.icon.split("|"),V="http://tongji.baidu.com/hm-web/welcome/ico?s="+c.id,W=("http:"==R?"http://eiv":"https://bs")+".baidu.com"+z[0]+"."+z[1];switch(z[1]){case "swf":var ha=z[2],ia=z[3],x="s="+V,u="HolmesIcon"+Q;y='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+u+'" width="'+ha+'" height="'+ia+'"><param name="movie" value="'+W+'" /><param name="flashvars" value="'+(x||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+
u+'" width="'+ha+'" height="'+ia+'" src="'+W+'" flashvars="'+(x||"")+'" allowscriptaccess="always" /></object>';break;case "gif":y='<a href="'+V+'" target="_blank"><img border="0" src="'+W+'" width="'+z[2]+'" height="'+z[3]+'"></a>';break;default:y='<a href="'+V+'" target="_blank">'+z[0]+"</a>"}document.write(y)}var N=document.location.hash.substring(1),xa=RegExp(c.id),ya=-1<document.referrer.indexOf("baidu.com")?l:n;if(N&&xa.test(N)&&ya){var O=document.createElement("script");O.setAttribute("type",
"text/javascript");O.setAttribute("charset","utf-8");O.setAttribute("src",R+"//"+c.js+C(N,"jn")+"."+C(N,"sx")+"?"+a.a.rnd);var ja=document.getElementsByTagName("script")[0];ja.parentNode.insertBefore(O,ja)}a.i&&a.i();a.h&&a.h();if(c.rec||c.trust)a.a.nv?(a.c=encodeURIComponent(document.referrer),window.sessionStorage?v("Hm_from_"+c.id,a.c):ga("Hm_from_"+c.id,a.c,864E5)):a.c=(window.sessionStorage?w("Hm_from_"+c.id):la("Hm_from_"+c.id))||"";a.j&&a.j();a.k&&a.k();B(window,"unload",ua(a));var A=window._hmt;
if(A&&A.length)for(y=0;y<A.length;y++){var H=A[y];switch(H[0]){case "_setAccount":1<H.length&&/^[0-9a-z]{32}$/.test(H[1])&&(a.a.api|=1,window._bdhm_account=H[1]);break;case "_setAutoPageview":if(1<H.length){var X=H[1];if(n===X||l===X)a.a.api|=2,window._bdhm_autoPageview=X}}}if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var P=window._hmt;if(P&&P.length)for(var A=0,za=P.length;A<za;A++)a.l(P[A]);window._hmt=a.o}if("undefined"===typeof window._bdhm_autoPageview||
window._bdhm_autoPageview===l)a.g=l,a.a.et=0,a.a.ep="",T(a)}catch(ka){a=[],a.push("si="+c.id),a.push("n="+encodeURIComponent(ka.name)),a.push("m="+encodeURIComponent(ka.message)),a.push("r="+encodeURIComponent(document.referrer)),L(R+"//hm.baidu.com/hm.gif?"+a.join("&"))}}
function ta(a){for(var b=[],d=0,e=ma.length;d<e;d++){var f=ma[d],g=a.a[f];"undefined"!=typeof g&&""!==g&&b.push(f+"="+encodeURIComponent(g))}d=a.a.et;(0===d||90===d)&&a.a.rt&&b.push("rt="+encodeURIComponent(a.a.rt));return b.join("&")}
function qa(){var a="Hm_cv_"+c.id;try{if(s(a,"",{domain:oa(),path:pa(),f:-1}),window.sessionStorage&&window.sessionStorage.removeItem(a),window.localStorage)window.localStorage.removeItem(a);else if(I())try{F.load(document.location.hostname),F.removeAttribute(a),F.save(document.location.hostname)}catch(b){}}catch(d){}}function pa(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&wa(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"}
function oa(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(Z(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a}function Y(a){for(var b=0;b<c.dm.length;b++)if(-1<c.dm[b].indexOf("/")){if(wa(a,c.dm[b]))return l}else{var d=D(a);if(d&&Z(d,c.dm[b]))return l}return n}function wa(a,b){a=a.replace(/^https?:\/\//,"");return 0==a.indexOf(b)}function Z(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length}
S.prototype.i=function(){B(document,"click",Aa(this));for(var a=c.etrk.length,b=0;b<a;b++){var d=c.etrk[b],e=document.getElementById(d.id);e&&B(e,d.eventType,Ba(this))}};function Ba(a){return function(b){(b.target||b.srcElement).setAttribute("HM_fix",b.clientX+":"+b.clientY);a.a.et=1;a.a.ep="{id:"+this.id+",eventType:"+b.type+"}";T(a)}}
function Aa(a){return function(b){var d=b.target||b.srcElement;if(d){var e=d.getAttribute("HM_fix"),f=b.clientX+":"+b.clientY;if(e&&e==f)d.removeAttribute("HM_fix");else if(e=c.etrk.length,0<e){for(f={};d&&d!=document.body;)d.id&&(f[d.id]=""),d=d.parentNode;for(d=0;d<e;d++){var g=c.etrk[d];f.hasOwnProperty(g.id)&&(a.a.et=1,a.a.ep="{id:"+g.id+",eventType:"+b.type+"}",T(a))}}}}}
S.prototype.h=function(){var a=this;c.ctrk&&(B(document,"mouseup",Ca(this)),B(window,"unload",function(){$(a)}),setInterval(function(){$(a)},6E5))};
function Ca(a){return function(b){var d,e;aa?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),d=b.clientX+d,e=b.clientY+e):(d=b.pageX,e=b.pageY);var f=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:d-=f/2;break;case 2:d-=f}d="{x:"+d+",y:"+e+",";b=b.target||b.srcElement;if("a"!=b.tagName.toLowerCase())a:{for(e="A";(b=b.parentNode)&&1==b.nodeType;)if(b.tagName==
e)break a;b=m}b=d=b?d+("t:a,u:"+encodeURIComponent(b.href)+"}"):d+"t:b}";""!=b&&(d=(R+"//hm.baidu.com/hm.gif?"+ta(a).replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+b+"]"))).length,1024<d+10||(1024<d+encodeURIComponent(a.b.join(",")+(a.b.length?",":"")).length+10&&$(a),a.b.push(b),(10<=a.b.length||/t:a/.test(b))&&$(a)))}}function $(a){0!=a.b.length&&(a.a.et=2,a.a.ep="["+a.b.join(",")+"]",T(a),a.b=[])}
S.prototype.j=function(){var a=this;c.rec&&p(function(){for(var b=0,d=c.rp.length;b<d;b++){var e=c.rp[b][0],f=c.rp[b][1],g=document.getElementById("hm_t_"+e);if(f&&!(2==f&&!g||g&&""!=g.innerHTML)){g=document.createElement("script");g.charset="utf-8";var h=Math.round(2147483647*Math.random());g.src=4==f?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+e,"rnd="+h].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+e,"from="+a.c,"referer="+encodeURIComponent(document.referrer),"title="+
encodeURIComponent(document.title),"rnd="+h].join("&");e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(g,e)}}})};
S.prototype.k=function(){if(c.trust&&c.vcard&&"https:"!=R){var a=document.createElement("script");a.charset="utf-8";a.src="http://trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+this.c,"rnd="+Math.round(2147483647*Math.random())].join("&");var b=document.getElementsByTagName("script")[0];b.parentNode.appendChild(a,b)}};
var va=function(){function a(){clearTimeout(J);var b;x&&(b="visible"==document[x]);u&&(b=!document[u]);f="undefined"==typeof b?l:b;if((!e||!g)&&f&&h)t=l,q=+new Date;else if(e&&g&&(!f||!h))t=n,G+=+new Date-q;e=f;g=h;J=setTimeout(a,100)}function b(a){var b=document,d="";if(a in b)d=a;else for(var e=["webkit","ms","moz","o"],f=0;f<e.length;f++){var g=e[f]+a.charAt(0).toUpperCase()+a.slice(1);if(g in b){d=g;break}}return d}function d(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))h=
"focus"==b.type||"focusin"==b.type?l:n,a()}var e=l,f=l,g=l,h=l,k=+new Date,q=k,G=0,t=l,x=b("visibilityState"),u=b("hidden"),J;a();(function(){var b=x.replace(/[vV]isibilityState/,"visibilitychange");B(document,b,a);B(window,"pageshow",a);B(window,"pagehide",a);"object"==typeof document.onfocusin?(B(document,"focusin",d),B(document,"focusout",d)):(B(window,"focus",d),B(window,"blur",d))})();return{n:function(){return+new Date-k},m:function(){return t?+new Date-q+G:G}}}();new S;})();
