//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Spell { get; set; }
        public string Alias { get; set; }
        public short Age { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public int SubCompanyId { get; set; }
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        public int WorkgroupId { get; set; }
        public int DutyId { get; set; }
        public string IDCard { get; set; }
        public string BankCode { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ShortNumber { get; set; }
        public string Telephone { get; set; }
        public string OICQ { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeZipCode { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeFax { get; set; }
        public Nullable<int> EducationId { get; set; }
        public string School { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string Major { get; set; }
        public int DegreeId { get; set; }
        public int TitleId { get; set; }
        public Nullable<System.DateTime> TitleDate { get; set; }
        public int TitleLevelId { get; set; }
        public string WorkingDate { get; set; }
        public Nullable<System.DateTime> JoinInDate { get; set; }
        public string HomeZipCode { get; set; }
        public string HomeAddress { get; set; }
        public string HomePhone { get; set; }
        public string HomeFax { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string NativePlace { get; set; }
        public Nullable<int> PartyId { get; set; }
        public Nullable<int> NationId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<int> WorkingPropertyId { get; set; }
        public string Competency { get; set; }
        public string EmergencyContact { get; set; }
        public Nullable<bool> IsDimission { get; set; }
        public Nullable<System.DateTime> DimissionDate { get; set; }
        public string DimissionCause { get; set; }
        public string DimissionWhither { get; set; }
        public string Remark { get; set; }
        public int SortIndex { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
