//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLogDetails
    {
        public int ID { get; set; }
        public int SyslogId { get; set; }
        public string FieldName { get; set; }
        public string FieldText { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public string Remark { get; set; }
    }
}
