//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPurview
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int PurviewId { get; set; }
        public int RoleId { get; set; }
        public bool HasRight { get; set; }
    }
}
