//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Spell { get; set; }
        public string Alias { get; set; }
        public int RoleId { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string OICQ { get; set; }
        public int DutyId { get; set; }
        public Nullable<int> TitleId { get; set; }
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        public int WorkgroupId { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> PreviousVisit { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public string Remark { get; set; }
        public bool IsEnable { get; set; }
        public int SortIndex { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
