//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.References.BPMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BPMService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        int Login(out int systemId, out int userId, out string userName, out string xmlRoleList, string systemCode, string account, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogOut", ReplyAction="http://tempuri.org/IService/LogOutResponse")]
        int LogOut(int systemId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginChangePassword", ReplyAction="http://tempuri.org/IService/LoginChangePasswordResponse")]
        int LoginChangePassword(int userId, string oldPwd, string newPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogGetUserMenuList", ReplyAction="http://tempuri.org/IService/LogGetUserMenuListResponse")]
        string LogGetUserMenuList(int systemId, int roleId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictGetList", ReplyAction="http://tempuri.org/IService/DataDictGetListResponse")]
        string DataDictGetList(string xmlCredentials, int systemId, int dictType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictGetModel", ReplyAction="http://tempuri.org/IService/DataDictGetModelResponse")]
        string DataDictGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictAdd", ReplyAction="http://tempuri.org/IService/DataDictAddResponse")]
        int DataDictAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictEdit", ReplyAction="http://tempuri.org/IService/DataDictEditResponse")]
        int DataDictEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictDelete", ReplyAction="http://tempuri.org/IService/DataDictDeleteResponse")]
        int DataDictDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictNameIsRepeat", ReplyAction="http://tempuri.org/IService/DataDictNameIsRepeatResponse")]
        bool DataDictNameIsRepeat(string xmlCredentials, int dictType, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DataDictCodeIsRepeat", ReplyAction="http://tempuri.org/IService/DataDictCodeIsRepeatResponse")]
        bool DataDictCodeIsRepeat(string xmlCredentials, int dictType, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EmployeeGetList", ReplyAction="http://tempuri.org/IService/EmployeeGetListResponse")]
        string EmployeeGetList(out int count, string xmlCredentials, int category, int orgaId, int searchType, string keyWord, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EmployeeGetModel", ReplyAction="http://tempuri.org/IService/EmployeeGetModelResponse")]
        string EmployeeGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EmployeeAdd", ReplyAction="http://tempuri.org/IService/EmployeeAddResponse")]
        int EmployeeAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EmployeeEdit", ReplyAction="http://tempuri.org/IService/EmployeeEditResponse")]
        int EmployeeEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EmployeeCodeIsRepeat", ReplyAction="http://tempuri.org/IService/EmployeeCodeIsRepeatResponse")]
        bool EmployeeCodeIsRepeat(string xmlCredentials, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IPBlackGetList", ReplyAction="http://tempuri.org/IService/IPBlackGetListResponse")]
        string IPBlackGetList(string xmlCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IPBlackGetModel", ReplyAction="http://tempuri.org/IService/IPBlackGetModelResponse")]
        string IPBlackGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IPBlackAdd", ReplyAction="http://tempuri.org/IService/IPBlackAddResponse")]
        int IPBlackAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IPBlackEdit", ReplyAction="http://tempuri.org/IService/IPBlackEditResponse")]
        int IPBlackEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IPBlackDelete", ReplyAction="http://tempuri.org/IService/IPBlackDeleteResponse")]
        int IPBlackDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuGetList", ReplyAction="http://tempuri.org/IService/MenuGetListResponse")]
        string MenuGetList(string xmlCredentials, int systemId, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuGetModel", ReplyAction="http://tempuri.org/IService/MenuGetModelResponse")]
        string MenuGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuAdd", ReplyAction="http://tempuri.org/IService/MenuAddResponse")]
        int MenuAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuEdit", ReplyAction="http://tempuri.org/IService/MenuEditResponse")]
        int MenuEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuDelete", ReplyAction="http://tempuri.org/IService/MenuDeleteResponse")]
        int MenuDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuNameIsRepeat", ReplyAction="http://tempuri.org/IService/MenuNameIsRepeatResponse")]
        bool MenuNameIsRepeat(string xmlCredentials, int systemId, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MenuCodeIsRepeat", ReplyAction="http://tempuri.org/IService/MenuCodeIsRepeatResponse")]
        bool MenuCodeIsRepeat(string xmlCredentials, int systemId, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganGetList", ReplyAction="http://tempuri.org/IService/OrganGetListResponse")]
        string OrganGetList(string xmlCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganGetModel", ReplyAction="http://tempuri.org/IService/OrganGetModelResponse")]
        string OrganGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganAdd", ReplyAction="http://tempuri.org/IService/OrganAddResponse")]
        int OrganAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganEdit", ReplyAction="http://tempuri.org/IService/OrganEditResponse")]
        int OrganEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganDelete", ReplyAction="http://tempuri.org/IService/OrganDeleteResponse")]
        int OrganDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganNameIsRepeat", ReplyAction="http://tempuri.org/IService/OrganNameIsRepeatResponse")]
        bool OrganNameIsRepeat(string xmlCredentials, int parentId, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OrganCodeIsRepeat", ReplyAction="http://tempuri.org/IService/OrganCodeIsRepeatResponse")]
        bool OrganCodeIsRepeat(string xmlCredentials, int parentId, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PubGetSystemList", ReplyAction="http://tempuri.org/IService/PubGetSystemListResponse")]
        string PubGetSystemList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PubGetRoleList", ReplyAction="http://tempuri.org/IService/PubGetRoleListResponse")]
        string PubGetRoleList(int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PubGetAllPurview", ReplyAction="http://tempuri.org/IService/PubGetAllPurviewResponse")]
        string PubGetAllPurview(int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PubGetUserPurviewList", ReplyAction="http://tempuri.org/IService/PubGetUserPurviewListResponse")]
        string PubGetUserPurviewList(int systemId, int roleId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PubGetUserByDeptId", ReplyAction="http://tempuri.org/IService/PubGetUserByDeptIdResponse")]
        string PubGetUserByDeptId(int deptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewGetModuleList", ReplyAction="http://tempuri.org/IService/PurviewGetModuleListResponse")]
        string PurviewGetModuleList(out int count, string xmlCredentials, int systemId, string moduleName, string moduleCode, int isEnable, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewGetFunctionList", ReplyAction="http://tempuri.org/IService/PurviewGetFunctionListResponse")]
        string PurviewGetFunctionList(out int count, string xmlCredentials, int systemId, int moduleId, string functionName, string functionCode, int isEnable, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewGetActionList", ReplyAction="http://tempuri.org/IService/PurviewGetActionListResponse")]
        string PurviewGetActionList(out int count, string xmlCredentials, int systemId, int moduleId, int functionId, string actionName, string actionCode, int isEnable, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewGetListByParentId", ReplyAction="http://tempuri.org/IService/PurviewGetListByParentIdResponse")]
        string PurviewGetListByParentId(string xmlCredentials, int systemId, int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewGetModel", ReplyAction="http://tempuri.org/IService/PurviewGetModelResponse")]
        string PurviewGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewAdd", ReplyAction="http://tempuri.org/IService/PurviewAddResponse")]
        int PurviewAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewEdit", ReplyAction="http://tempuri.org/IService/PurviewEditResponse")]
        int PurviewEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewDelete", ReplyAction="http://tempuri.org/IService/PurviewDeleteResponse")]
        int PurviewDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewNameIsRepeat", ReplyAction="http://tempuri.org/IService/PurviewNameIsRepeatResponse")]
        bool PurviewNameIsRepeat(string xmlCredentials, int systemId, int parentId, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PurviewCodeIsRepeat", ReplyAction="http://tempuri.org/IService/PurviewCodeIsRepeatResponse")]
        bool PurviewCodeIsRepeat(string xmlCredentials, int systemId, int parentId, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleGetList", ReplyAction="http://tempuri.org/IService/RoleGetListResponse")]
        string RoleGetList(string xmlCredentials, int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleGetModel", ReplyAction="http://tempuri.org/IService/RoleGetModelResponse")]
        string RoleGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleAdd", ReplyAction="http://tempuri.org/IService/RoleAddResponse")]
        int RoleAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleEdit", ReplyAction="http://tempuri.org/IService/RoleEditResponse")]
        int RoleEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleDelete", ReplyAction="http://tempuri.org/IService/RoleDeleteResponse")]
        int RoleDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleNameIsRepeat", ReplyAction="http://tempuri.org/IService/RoleNameIsRepeatResponse")]
        bool RoleNameIsRepeat(string xmlCredentials, int systemId, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleCodeIsRepeat", ReplyAction="http://tempuri.org/IService/RoleCodeIsRepeatResponse")]
        bool RoleCodeIsRepeat(string xmlCredentials, int systemId, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RolePurviewSet", ReplyAction="http://tempuri.org/IService/RolePurviewSetResponse")]
        int RolePurviewSet(string xmlCredentials, int roleId, int[] purviewIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleGetPurviewList", ReplyAction="http://tempuri.org/IService/RoleGetPurviewListResponse")]
        string RoleGetPurviewList(string xmlCredentials, int systemId, int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleMembers", ReplyAction="http://tempuri.org/IService/RoleMembersResponse")]
        string RoleMembers(string xmlCredentials, int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleMemberAdd", ReplyAction="http://tempuri.org/IService/RoleMemberAddResponse")]
        int RoleMemberAdd(string xmlCredentials, int roleId, int[] userIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RoleMemberDelete", ReplyAction="http://tempuri.org/IService/RoleMemberDeleteResponse")]
        int RoleMemberDelete(string xmlCredentials, int roleId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCacheKeyList", ReplyAction="http://tempuri.org/IService/GetCacheKeyListResponse")]
        string GetCacheKeyList(out int count, string xmlCredentials, string keyWord, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CacheClear", ReplyAction="http://tempuri.org/IService/CacheClearResponse")]
        int CacheClear(string xmlCredentials, string[] lstKeyWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SysLogGetList", ReplyAction="http://tempuri.org/IService/SysLogGetListResponse")]
        string SysLogGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, int operationType, string moduleName, string account, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SysLogClear", ReplyAction="http://tempuri.org/IService/SysLogClearResponse")]
        bool SysLogClear(string xmlCredentials, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SysLoginLogGetList", ReplyAction="http://tempuri.org/IService/SysLoginLogGetListResponse")]
        string SysLoginLogGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, string account, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SysLoginLogClear", ReplyAction="http://tempuri.org/IService/SysLoginLogClearResponse")]
        bool SysLoginLogClear(string xmlCredentials, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemExceptionGetList", ReplyAction="http://tempuri.org/IService/SystemExceptionGetListResponse")]
        string SystemExceptionGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemExceptionClear", ReplyAction="http://tempuri.org/IService/SystemExceptionClearResponse")]
        bool SystemExceptionClear(string xmlCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemGetList", ReplyAction="http://tempuri.org/IService/SystemGetListResponse")]
        string SystemGetList(string xmlCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemGetModel", ReplyAction="http://tempuri.org/IService/SystemGetModelResponse")]
        string SystemGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemAdd", ReplyAction="http://tempuri.org/IService/SystemAddResponse")]
        int SystemAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemEdit", ReplyAction="http://tempuri.org/IService/SystemEditResponse")]
        int SystemEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemDelete", ReplyAction="http://tempuri.org/IService/SystemDeleteResponse")]
        int SystemDelete(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemNameIsRepeat", ReplyAction="http://tempuri.org/IService/SystemNameIsRepeatResponse")]
        bool SystemNameIsRepeat(string xmlCredentials, string name, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SystemCodeIsRepeat", ReplyAction="http://tempuri.org/IService/SystemCodeIsRepeatResponse")]
        bool SystemCodeIsRepeat(string xmlCredentials, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserGetList", ReplyAction="http://tempuri.org/IService/UserGetListResponse")]
        string UserGetList(out int count, string xmlCredentials, int searchType, string keyWord, int isEnable, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserGetModel", ReplyAction="http://tempuri.org/IService/UserGetModelResponse")]
        string UserGetModel(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserAdd", ReplyAction="http://tempuri.org/IService/UserAddResponse")]
        int UserAdd(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserEdit", ReplyAction="http://tempuri.org/IService/UserEditResponse")]
        int UserEdit(string xmlCredentials, string xmlModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserAccountIsRepeat", ReplyAction="http://tempuri.org/IService/UserAccountIsRepeatResponse")]
        bool UserAccountIsRepeat(string xmlCredentials, string account, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserCodeIsRepeat", ReplyAction="http://tempuri.org/IService/UserCodeIsRepeatResponse")]
        bool UserCodeIsRepeat(string xmlCredentials, string code, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserPasswordReset", ReplyAction="http://tempuri.org/IService/UserPasswordResetResponse")]
        bool UserPasswordReset(string xmlCredentials, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserGetPurviewList", ReplyAction="http://tempuri.org/IService/UserGetPurviewListResponse")]
        string UserGetPurviewList(string xmlCredentials, int systemId, int roleId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserPurviewSet", ReplyAction="http://tempuri.org/IService/UserPurviewSetResponse")]
        int UserPurviewSet(string xmlCredentials, string[] lstModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserPurviewReset", ReplyAction="http://tempuri.org/IService/UserPurviewResetResponse")]
        int UserPurviewReset(string xmlCredentials, int systemId, int roleId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserRoleSet", ReplyAction="http://tempuri.org/IService/UserRoleSetResponse")]
        int UserRoleSet(string xmlCredentials, int systemId, int userId, int[] lstRoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UserRoleGetList", ReplyAction="http://tempuri.org/IService/UserRoleGetListResponse")]
        string UserRoleGetList(string xmlCredentials, int systemId, int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BPMS.References.BPMService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BPMS.References.BPMService.IService>, BPMS.References.BPMService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(out int systemId, out int userId, out string userName, out string xmlRoleList, string systemCode, string account, string pwd) {
            return base.Channel.Login(out systemId, out userId, out userName, out xmlRoleList, systemCode, account, pwd);
        }
        
        public int LogOut(int systemId, int userId) {
            return base.Channel.LogOut(systemId, userId);
        }
        
        public int LoginChangePassword(int userId, string oldPwd, string newPwd) {
            return base.Channel.LoginChangePassword(userId, oldPwd, newPwd);
        }
        
        public string LogGetUserMenuList(int systemId, int roleId, int userId) {
            return base.Channel.LogGetUserMenuList(systemId, roleId, userId);
        }
        
        public string DataDictGetList(string xmlCredentials, int systemId, int dictType) {
            return base.Channel.DataDictGetList(xmlCredentials, systemId, dictType);
        }
        
        public string DataDictGetModel(string xmlCredentials, int id) {
            return base.Channel.DataDictGetModel(xmlCredentials, id);
        }
        
        public int DataDictAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.DataDictAdd(xmlCredentials, xmlModel);
        }
        
        public int DataDictEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.DataDictEdit(xmlCredentials, xmlModel);
        }
        
        public int DataDictDelete(string xmlCredentials, int id) {
            return base.Channel.DataDictDelete(xmlCredentials, id);
        }
        
        public bool DataDictNameIsRepeat(string xmlCredentials, int dictType, string name, int id) {
            return base.Channel.DataDictNameIsRepeat(xmlCredentials, dictType, name, id);
        }
        
        public bool DataDictCodeIsRepeat(string xmlCredentials, int dictType, string code, int id) {
            return base.Channel.DataDictCodeIsRepeat(xmlCredentials, dictType, code, id);
        }
        
        public string EmployeeGetList(out int count, string xmlCredentials, int category, int orgaId, int searchType, string keyWord, int pageIndex, int pageSize) {
            return base.Channel.EmployeeGetList(out count, xmlCredentials, category, orgaId, searchType, keyWord, pageIndex, pageSize);
        }
        
        public string EmployeeGetModel(string xmlCredentials, int id) {
            return base.Channel.EmployeeGetModel(xmlCredentials, id);
        }
        
        public int EmployeeAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.EmployeeAdd(xmlCredentials, xmlModel);
        }
        
        public int EmployeeEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.EmployeeEdit(xmlCredentials, xmlModel);
        }
        
        public bool EmployeeCodeIsRepeat(string xmlCredentials, string code, int id) {
            return base.Channel.EmployeeCodeIsRepeat(xmlCredentials, code, id);
        }
        
        public string IPBlackGetList(string xmlCredentials) {
            return base.Channel.IPBlackGetList(xmlCredentials);
        }
        
        public string IPBlackGetModel(string xmlCredentials, int id) {
            return base.Channel.IPBlackGetModel(xmlCredentials, id);
        }
        
        public int IPBlackAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.IPBlackAdd(xmlCredentials, xmlModel);
        }
        
        public int IPBlackEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.IPBlackEdit(xmlCredentials, xmlModel);
        }
        
        public int IPBlackDelete(string xmlCredentials, int id) {
            return base.Channel.IPBlackDelete(xmlCredentials, id);
        }
        
        public string MenuGetList(string xmlCredentials, int systemId, int parentId) {
            return base.Channel.MenuGetList(xmlCredentials, systemId, parentId);
        }
        
        public string MenuGetModel(string xmlCredentials, int id) {
            return base.Channel.MenuGetModel(xmlCredentials, id);
        }
        
        public int MenuAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.MenuAdd(xmlCredentials, xmlModel);
        }
        
        public int MenuEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.MenuEdit(xmlCredentials, xmlModel);
        }
        
        public int MenuDelete(string xmlCredentials, int id) {
            return base.Channel.MenuDelete(xmlCredentials, id);
        }
        
        public bool MenuNameIsRepeat(string xmlCredentials, int systemId, string name, int id) {
            return base.Channel.MenuNameIsRepeat(xmlCredentials, systemId, name, id);
        }
        
        public bool MenuCodeIsRepeat(string xmlCredentials, int systemId, string code, int id) {
            return base.Channel.MenuCodeIsRepeat(xmlCredentials, systemId, code, id);
        }
        
        public string OrganGetList(string xmlCredentials) {
            return base.Channel.OrganGetList(xmlCredentials);
        }
        
        public string OrganGetModel(string xmlCredentials, int id) {
            return base.Channel.OrganGetModel(xmlCredentials, id);
        }
        
        public int OrganAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.OrganAdd(xmlCredentials, xmlModel);
        }
        
        public int OrganEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.OrganEdit(xmlCredentials, xmlModel);
        }
        
        public int OrganDelete(string xmlCredentials, int id) {
            return base.Channel.OrganDelete(xmlCredentials, id);
        }
        
        public bool OrganNameIsRepeat(string xmlCredentials, int parentId, string name, int id) {
            return base.Channel.OrganNameIsRepeat(xmlCredentials, parentId, name, id);
        }
        
        public bool OrganCodeIsRepeat(string xmlCredentials, int parentId, string code, int id) {
            return base.Channel.OrganCodeIsRepeat(xmlCredentials, parentId, code, id);
        }
        
        public string PubGetSystemList() {
            return base.Channel.PubGetSystemList();
        }
        
        public string PubGetRoleList(int systemId) {
            return base.Channel.PubGetRoleList(systemId);
        }
        
        public string PubGetAllPurview(int systemId) {
            return base.Channel.PubGetAllPurview(systemId);
        }
        
        public string PubGetUserPurviewList(int systemId, int roleId, int userId) {
            return base.Channel.PubGetUserPurviewList(systemId, roleId, userId);
        }
        
        public string PubGetUserByDeptId(int deptId) {
            return base.Channel.PubGetUserByDeptId(deptId);
        }
        
        public string PurviewGetModuleList(out int count, string xmlCredentials, int systemId, string moduleName, string moduleCode, int isEnable, int pageIndex, int pageSize) {
            return base.Channel.PurviewGetModuleList(out count, xmlCredentials, systemId, moduleName, moduleCode, isEnable, pageIndex, pageSize);
        }
        
        public string PurviewGetFunctionList(out int count, string xmlCredentials, int systemId, int moduleId, string functionName, string functionCode, int isEnable, int pageIndex, int pageSize) {
            return base.Channel.PurviewGetFunctionList(out count, xmlCredentials, systemId, moduleId, functionName, functionCode, isEnable, pageIndex, pageSize);
        }
        
        public string PurviewGetActionList(out int count, string xmlCredentials, int systemId, int moduleId, int functionId, string actionName, string actionCode, int isEnable, int pageIndex, int pageSize) {
            return base.Channel.PurviewGetActionList(out count, xmlCredentials, systemId, moduleId, functionId, actionName, actionCode, isEnable, pageIndex, pageSize);
        }
        
        public string PurviewGetListByParentId(string xmlCredentials, int systemId, int parentId) {
            return base.Channel.PurviewGetListByParentId(xmlCredentials, systemId, parentId);
        }
        
        public string PurviewGetModel(string xmlCredentials, int id) {
            return base.Channel.PurviewGetModel(xmlCredentials, id);
        }
        
        public int PurviewAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.PurviewAdd(xmlCredentials, xmlModel);
        }
        
        public int PurviewEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.PurviewEdit(xmlCredentials, xmlModel);
        }
        
        public int PurviewDelete(string xmlCredentials, int id) {
            return base.Channel.PurviewDelete(xmlCredentials, id);
        }
        
        public bool PurviewNameIsRepeat(string xmlCredentials, int systemId, int parentId, string name, int id) {
            return base.Channel.PurviewNameIsRepeat(xmlCredentials, systemId, parentId, name, id);
        }
        
        public bool PurviewCodeIsRepeat(string xmlCredentials, int systemId, int parentId, string code, int id) {
            return base.Channel.PurviewCodeIsRepeat(xmlCredentials, systemId, parentId, code, id);
        }
        
        public string RoleGetList(string xmlCredentials, int systemId) {
            return base.Channel.RoleGetList(xmlCredentials, systemId);
        }
        
        public string RoleGetModel(string xmlCredentials, int id) {
            return base.Channel.RoleGetModel(xmlCredentials, id);
        }
        
        public int RoleAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.RoleAdd(xmlCredentials, xmlModel);
        }
        
        public int RoleEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.RoleEdit(xmlCredentials, xmlModel);
        }
        
        public int RoleDelete(string xmlCredentials, int id) {
            return base.Channel.RoleDelete(xmlCredentials, id);
        }
        
        public bool RoleNameIsRepeat(string xmlCredentials, int systemId, string name, int id) {
            return base.Channel.RoleNameIsRepeat(xmlCredentials, systemId, name, id);
        }
        
        public bool RoleCodeIsRepeat(string xmlCredentials, int systemId, string code, int id) {
            return base.Channel.RoleCodeIsRepeat(xmlCredentials, systemId, code, id);
        }
        
        public int RolePurviewSet(string xmlCredentials, int roleId, int[] purviewIdList) {
            return base.Channel.RolePurviewSet(xmlCredentials, roleId, purviewIdList);
        }
        
        public string RoleGetPurviewList(string xmlCredentials, int systemId, int roleId) {
            return base.Channel.RoleGetPurviewList(xmlCredentials, systemId, roleId);
        }
        
        public string RoleMembers(string xmlCredentials, int roleId) {
            return base.Channel.RoleMembers(xmlCredentials, roleId);
        }
        
        public int RoleMemberAdd(string xmlCredentials, int roleId, int[] userIdList) {
            return base.Channel.RoleMemberAdd(xmlCredentials, roleId, userIdList);
        }
        
        public int RoleMemberDelete(string xmlCredentials, int roleId, int userId) {
            return base.Channel.RoleMemberDelete(xmlCredentials, roleId, userId);
        }
        
        public string GetCacheKeyList(out int count, string xmlCredentials, string keyWord, int pageIndex, int pageSize) {
            return base.Channel.GetCacheKeyList(out count, xmlCredentials, keyWord, pageIndex, pageSize);
        }
        
        public int CacheClear(string xmlCredentials, string[] lstKeyWord) {
            return base.Channel.CacheClear(xmlCredentials, lstKeyWord);
        }
        
        public string SysLogGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, int operationType, string moduleName, string account, int pageIndex, int pageSize) {
            return base.Channel.SysLogGetList(out count, xmlCredentials, startDate, endDate, operationType, moduleName, account, pageIndex, pageSize);
        }
        
        public bool SysLogClear(string xmlCredentials, System.DateTime endDate) {
            return base.Channel.SysLogClear(xmlCredentials, endDate);
        }
        
        public string SysLoginLogGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, string account, int pageIndex, int pageSize) {
            return base.Channel.SysLoginLogGetList(out count, xmlCredentials, startDate, endDate, account, pageIndex, pageSize);
        }
        
        public bool SysLoginLogClear(string xmlCredentials, System.DateTime endDate) {
            return base.Channel.SysLoginLogClear(xmlCredentials, endDate);
        }
        
        public string SystemExceptionGetList(out int count, string xmlCredentials, System.DateTime startDate, System.DateTime endDate, int pageIndex, int pageSize) {
            return base.Channel.SystemExceptionGetList(out count, xmlCredentials, startDate, endDate, pageIndex, pageSize);
        }
        
        public bool SystemExceptionClear(string xmlCredentials) {
            return base.Channel.SystemExceptionClear(xmlCredentials);
        }
        
        public string SystemGetList(string xmlCredentials) {
            return base.Channel.SystemGetList(xmlCredentials);
        }
        
        public string SystemGetModel(string xmlCredentials, int id) {
            return base.Channel.SystemGetModel(xmlCredentials, id);
        }
        
        public int SystemAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.SystemAdd(xmlCredentials, xmlModel);
        }
        
        public int SystemEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.SystemEdit(xmlCredentials, xmlModel);
        }
        
        public int SystemDelete(string xmlCredentials, int id) {
            return base.Channel.SystemDelete(xmlCredentials, id);
        }
        
        public bool SystemNameIsRepeat(string xmlCredentials, string name, int id) {
            return base.Channel.SystemNameIsRepeat(xmlCredentials, name, id);
        }
        
        public bool SystemCodeIsRepeat(string xmlCredentials, string code, int id) {
            return base.Channel.SystemCodeIsRepeat(xmlCredentials, code, id);
        }
        
        public string UserGetList(out int count, string xmlCredentials, int searchType, string keyWord, int isEnable, int pageIndex, int pageSize) {
            return base.Channel.UserGetList(out count, xmlCredentials, searchType, keyWord, isEnable, pageIndex, pageSize);
        }
        
        public string UserGetModel(string xmlCredentials, int id) {
            return base.Channel.UserGetModel(xmlCredentials, id);
        }
        
        public int UserAdd(string xmlCredentials, string xmlModel) {
            return base.Channel.UserAdd(xmlCredentials, xmlModel);
        }
        
        public int UserEdit(string xmlCredentials, string xmlModel) {
            return base.Channel.UserEdit(xmlCredentials, xmlModel);
        }
        
        public bool UserAccountIsRepeat(string xmlCredentials, string account, int id) {
            return base.Channel.UserAccountIsRepeat(xmlCredentials, account, id);
        }
        
        public bool UserCodeIsRepeat(string xmlCredentials, string code, int id) {
            return base.Channel.UserCodeIsRepeat(xmlCredentials, code, id);
        }
        
        public bool UserPasswordReset(string xmlCredentials, int id) {
            return base.Channel.UserPasswordReset(xmlCredentials, id);
        }
        
        public string UserGetPurviewList(string xmlCredentials, int systemId, int roleId, int userId) {
            return base.Channel.UserGetPurviewList(xmlCredentials, systemId, roleId, userId);
        }
        
        public int UserPurviewSet(string xmlCredentials, string[] lstModel) {
            return base.Channel.UserPurviewSet(xmlCredentials, lstModel);
        }
        
        public int UserPurviewReset(string xmlCredentials, int systemId, int roleId, int userId) {
            return base.Channel.UserPurviewReset(xmlCredentials, systemId, roleId, userId);
        }
        
        public int UserRoleSet(string xmlCredentials, int systemId, int userId, int[] lstRoleId) {
            return base.Channel.UserRoleSet(xmlCredentials, systemId, userId, lstRoleId);
        }
        
        public string UserRoleGetList(string xmlCredentials, int systemId, int userId) {
            return base.Channel.UserRoleGetList(xmlCredentials, systemId, userId);
        }
    }
}
